default: &default
    adapter: mysql
    username: root
    password: rootpass
    pool: 5
    encoding: utf8

production:
    <<: *default
    database: production_deploy_logger

development:
    <<: *default
    database: development_deploy_logger

test:
    <<: *default
    database: test_deploy_logger
