default: &default
    adapter: mysql
    host: localhost
    username: root
    password: rootpass
    pool: 5
    encoding: utf8

production:
    <<: *default
    database: deploy_logger_production

development:
    <<: *default
    database: deploy_logger_development

test:
    <<: *default
    database: deploy_logger_test
